format = """
$username\
$directory\
$git_branch\
$git_status
"""

right_format = """
$time\
$all\
$character
"""

[username]
show_always = true
style_user = "fg:#ffffff bg:#372A6C"
style_root = "fg:#ffffff bg:#372A6C"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "fg:#000000 bg:#eac54f"
format = "[ $path ]($style)"
disabled = false

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#ffffff bg:#e44729"
format = '[ $symbol $branch ]($style)'
disabled = false

[git_status]
style = "fg:#ffffff bg:#e44729"
format = '[$all_status$ahead_behind ]($style)'
disabled = false

[c]
symbol = ""
style = "fg:#ffffff bg:#840a2c"
format = '[ $symbol ($version) ]($style)'
disabled = false

[kubernetes]
style = "fg:#ffffff bg:#326ce5"
format = '[ on ﴱ ($user on )($cluster in )$context \($namespace\) ]($style)'
disabled = false

[golang]
symbol = ""
style = "fg:#ffffff bg:#007d9c"
format = '[ $symbol ($version) ]($style)'
disabled = false

[java]
symbol = ""
style = "fg:#ffffff bg:#007396"
format = '[ $symbol ($version) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "fg:#ffffff bg:#5fa04e"
format = '[ $symbol ($version) ]($style)'
disabled = false

[php]
symbol = ''
style = "fg:#ffffff bg:#4F5B93"
format = '[ $symbol ($version) ]($style)'
disabled = false

[rust]
symbol = ""
style = "fg:#ffffff bg:#a72145"
format = '[ $symbol ($version) ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#ffffff bg:#8250df"
format = '[  $time ]($style)'

[cmd_duration]
style = "fg:#000000 bg:yellow"
format = "[ took $duration ]($style)"

[character]
format = " $symbol"